---
title: "Mini-Project #01: Fiscal Characteristics of Major US Public Transit Systems"
author: "mt1536"
---

# Introduction

This is a small project in which I explore data from the [National Transit Database](https://www.transit.dot.gov/ntd) with the objective of finding facts and insights from the data. Instructions and further details provided by my professor Mr. Michael Weylandt, Ph.D can be found [here](https://michael-weylandt.com/STA9750/miniprojects/mini01.html). We will be using data such as farebox revenues, total number of trips, total number of vehicle miles traveled, and total revenues and expenses by source.

## Preparing the Data

To start with the project, I used the following code to download the data. Here we can see some tables being created with specific columns, then these new tables are joined.

```{r echo=TRUE, warning=FALSE, message=FALSE}
library(tidyverse)
library(DT)
setwd("C:/Users/MT/Desktop/R Coding/STA9750-2024-FALL")

FARES <- readxl::read_xlsx("2022_fare_revenue.xlsx") |>
    select(-`State/Parent NTD ID`, 
           -`Reporter Type`,
           -`Reporting Module`,
           -`TOS`,
           -`Passenger Paid Fares`,
           -`Organization Paid Fares`) |>
    filter(`Expense Type` == "Funds Earned During Period") |>
    select(-`Expense Type`) |>
    group_by(`NTD ID`,       # Sum over different `TOS` for the same `Mode`
             `Agency Name`,  # These are direct operated and sub-contracted 
             `Mode`) |>      # of the same transit modality
                             # Not a big effect in most munis (significant DO
                             # tends to get rid of sub-contractors), but we'll sum
                             # to unify different passenger experiences
    summarize(`Total Fares` = sum(`Total Fares`)) |>
    ungroup()

EXPENSES <- readr::read_csv("2022_expenses.csv") |>
    select(`NTD ID`, 
           `Agency`,
           `Total`, 
           `Mode`) |>
    mutate(`NTD ID` = as.integer(`NTD ID`)) |>
    rename(Expenses = Total) |>
    group_by(`NTD ID`, `Mode`) |>
    summarize(Expenses = sum(Expenses)) |>
    ungroup()

FINANCIALS <- inner_join(FARES, EXPENSES, join_by(`NTD ID`, `Mode`))

TRIPS <- readxl::read_xlsx("ridership.xlsx", sheet = "UPT") |>
            filter(`Mode/Type of Service Status` == "Active") |>
            select(-`Legacy NTD ID`, 
                   -`Reporter Type`, 
                   -`Mode/Type of Service Status`, 
                   -`UACE CD`, 
                   -`TOS`) |>
            pivot_longer(-c(`NTD ID`:`3 Mode`), 
                            names_to="month", 
                            values_to="UPT") |>
            drop_na() |>
            mutate(month=my(month)) # Parse _m_onth _y_ear date specs
MILES <- readxl::read_xlsx("ridership.xlsx", sheet="VRM") |>
            filter(`Mode/Type of Service Status` == "Active") |>
            select(-`Legacy NTD ID`, 
                   -`Reporter Type`, 
                   -`Mode/Type of Service Status`, 
                   -`UACE CD`, 
                   -`TOS`) |>
            pivot_longer(-c(`NTD ID`:`3 Mode`), 
                            names_to="month", 
                            values_to="VRM") |>
            drop_na() |>
            group_by(`NTD ID`, `Agency`, `UZA Name`, 
                     `Mode`, `3 Mode`, month) |>
            summarize(VRM = sum(VRM)) |>
            ungroup() |>
            mutate(month=my(month)) # Parse _m_onth _y_ear date specs

USAGE <- inner_join(TRIPS, MILES) |>
    mutate(`NTD ID` = as.integer(`NTD ID`))

sample_n(USAGE, 1000) |> 
  mutate(month=as.character(month)) |> 
  DT::datatable()
```

## Task 1: Creating Syntatic Names

After downloading the data, the first task is to create a synthetic name. The column `UZA Name` was renamed as `metro_area`:

```         
{r echo=TRUE, warning=FALSE, message=FALSE}
USAGE <- USAGE |> 
  rename(metro_area = `UZA Name`)
```

## Task 2: Recoding the Mode column

Mode column was recoded for easier understanding of data.  Details obtained from [here](https://www.transit.dot.gov/ntd/national-transit-database-ntd-glossary#D)

```
{r echo=TRUE, warning=FALSE, message=FALSE}
USAGE <- USAGE |>
  mutate(Mode = case_when(
    Mode == "AR" ~ "Alaska Railroad",
    Mode == "CB" ~ "Commuter Bus",
    Mode == "CC" ~ "Cable Car",
    Mode == "CR" ~ "Commuter Rail",
    Mode == "DR" ~ "Demand Response",
    Mode == "FB" ~ "Ferryboat",
    Mode == "HR" ~ "Heavy Rail",
    Mode == "IP" ~ "Inclined Plane",
    Mode == "LR" ~ "Light Rail",
    Mode == "MB" ~ "Bus",
    Mode == "MG" ~ "Monorail Automated Guideway",
    Mode == "PB" ~ "Publico",
    Mode == "RB" ~ "Bus Rapid Transit",
    Mode == "SR" ~ "Streetcar Rail",
    Mode == "TB" ~ "Trolleybus",
    Mode == "TR" ~ "Aerial Tramway",
    Mode == "VP" ~ "Vanpool",
    Mode == "YR" ~ "Hybrid Rail",
    TRUE ~ "Unknown"
))
```

Now we can see a table with cleaner data:

```
{r echo=TRUE, warning=FALSE, message=FALSE}
if(!require("DT")) install.packages("DT")
library(DT)

USAGE <- USAGE |> 
  select(-`3 Mode`)

sample_n(USAGE, 1000) |> 
  mutate(month = as.character(month)) |> 
  DT::datatable()
```

## Task 3: Answering Instructor Specified Questions with dplyr
Q1. What transit agency had the most total VRM in our data set?
The transit agency with the most  total VRM (Vehicle Revenue Miles) is MTA New York City Transit with around 69 billion in total VRM.

```
{r echo=TRUE, warning=FALSE, message=FALSE}
USAGE |>
  group_by(Agency) |>
  summarise(UPT_Total = sum(UPT)) |>
  arrange(desc(UPT_Total)) |>
  head(1) |>
  ungroup()

```

Q2. What transit mode had the most total VRM in our data set?
The transit mode with the most total VRM in our data set is bus with a total UPT (Unlinked Passenger Trips) of around 49 billion

```
USAGE |>
  group_by(Mode) |>
  summarise(VRM_Total = sum(VRM)) |>
  arrange(desc(VRM_Total)) |>
  head(1) |>
  ungroup()
# The data shows bus transportation had the most vehicle revenue miles "VRM"
# which is "The miles that vehicles are scheduled to or actually travel while in revenue service"
# https://www.transit.dot.gov/ntd/national-transit-database-ntd-glossary#V

```

Q3. How many trips were taken on the NYC Subway (Heavy Rail) in May 2024?
A total of 186,478,364 trips were taken on the NYC subway


```
{r echo=TRUE, warning=FALSE, message=FALSE}
colnames(USAGE)
nyc_filter_q3 <- USAGE |>
  filter(metro_area == "New York--Jersey City--Newark, NY--NJ", Mode == "Heavy Rail", month == "2024-05-01") |>
  summarise(May_2024_Trips = sum(UPT, na.rm = TRUE))
print(nyc_filter_q3)

```

Q4. What mode of transport had the longest average trip in May 2024? 
Note: This question can’t be answered with the current data


Q5. How much did NYC subway ridership fall between April 2019 and April 2020?
NYC subway ridership fell by approximately 91 during the dates indicated. This could be atributed to the Corona Virus pandemic of 2020.

```
{r echo=TRUE, warning=FALSE, message=FALSE}
nyc_filter_q5_part1 <- USAGE |>
  filter(metro_area == "New York--Jersey City--Newark, NY--NJ", Mode == "Heavy Rail", month == "2019-04-01") |>
  summarise(nyc_sub_2019 = sum(UPT, na.rm = TRUE))
nyc_filter_q5_part2 <- USAGE |>
  filter(metro_area == "New York--Jersey City--Newark, NY--NJ", Mode == "Heavy Rail", month == "2020-04-01") |>
  summarise(nyc_sub_2020 = sum(UPT, na.rm = TRUE))
nyc_filter_q5_part3=((nyc_filter_q5_part2-nyc_filter_q5_part1)/(nyc_filter_q5_part1))*100
print(nyc_filter_q5_part3)

```

## Task 4: Explore and Analyze: Find three more interesting transit facts in this data other than those above.
Q4.1 Which Agency has the most VRM per UPT?
I chose this question because  I believe this shows how efficiently an agency is using its resources. A lower Vehicle Revenue Miles to Unlinked Passenger Trips ratio would show that an Agency is able to maximize the usage of its vehicles in relation to the number of passanger trips. In this case the most efficient based on the previously mentioned definition would be New York City Department of Transportation with a ratio of .00942. However, this needs deeper analysis to determine its implications and flaws

```
{r echo=TRUE, warning=FALSE, message=FALSE}
vrm_per_upt <- USAGE |>
  group_by(Agency) |>
  summarise(UPT_Total = sum(UPT), VRM_Total = sum(VRM), VRM_per_UPT_ratio = (VRM_Total/UPT_Total)) |>
  ungroup() |>
  arrange(VRM_per_UPT_ratio) |>
  head(5)

print(vrm_per_upt)

```
Q4.2 What is the most used mode per metro area?
The most used mode per metro area is the bus

```
{r echo=TRUE, warning=FALSE, message=FALSE}
most_used_mode_per_metro_area <- USAGE |>
  group_by(metro_area, Mode) |>
  summarise(total_upt = sum(UPT, na.rm = TRUE), .groups = "drop") |>
  group_by(metro_area) |>
  slice(which.max(total_upt)) |>
  select(metro_area, Mode, total_upt)
print(most_used_mode_per_metro_area)


```
Q4.3 What are the top metro areas by mode?
New York Metro area is the top area by what I consider to be the most important modes of transportation: Heavy Rail, Bus, and Commuter Rail
```
{r echo=TRUE, warning=FALSE, message=FALSE}
top_metro_areas_by_mode <- USAGE |>
  group_by(Mode, metro_area) |>
  summarise(total_upt = sum(UPT, na.rm = TRUE)) |>
  group_by(Mode) |>
  slice(which.max(total_upt)) |>
  arrange(desc(total_upt))

print(top_metro_areas_by_mode)

```

## Task 5: Table Summarization

In this part of the project, I created a new table from USAGE that has annual total (sum) UPT and VRM for 2022

```
{r echo=TRUE, warning=FALSE, message=FALSE}

USAGE_2022_ANNUAL <- USAGE |>
  filter(year(month) == "2022") |>
  group_by(`NTD ID`, Agency, metro_area, Mode) |>
  summarise(UPT_Total = sum(UPT, na.rm = TRUE), VRM_Total = sum(VRM, na.rm = TRUE)) |>
  ungroup()

FINANCIALS <- FINANCIALS |>
  mutate(Mode = case_when(
    Mode == "AR" ~ "Alaska Railroad",
    Mode == "CB" ~ "Commuter Bus",
    Mode == "CC" ~ "Cable Car",
    Mode == "CR" ~ "Commuter Rail",
    Mode == "DR" ~ "Demand Response",
    Mode == "FB" ~ "Ferryboat",
    Mode == "HR" ~ "Heavy Rail",
    Mode == "IP" ~ "Inclined Plane",
    Mode == "LR" ~ "Light Rail",
    Mode == "MB" ~ "Bus",
    Mode == "MG" ~ "Monorail Automated Guideway",
    Mode == "PB" ~ "Publico",
    Mode == "RB" ~ "Bus Rapid Transit",
    Mode == "SR" ~ "Streetcar Rail",
    Mode == "TB" ~ "Trolleybus",
    Mode == "TR" ~ "Aerial Tramway",
    Mode == "VP" ~ "Vanpool",
    Mode == "YR" ~ "Hybrid Rail",
    TRUE ~ "Unknown"
  ))


USAGE_AND_FINANCIALS <- left_join(USAGE_2022_ANNUAL, FINANCIALS, 
  join_by(`NTD ID`, "Mode")) |>
  drop_na()

colnames(USAGE_2022_ANNUAL)

sample_n(USAGE_2022_ANNUAL, 1141) |> 
    DT::datatable()
```

## Task 6: Farebox Recovery Among All Systems

Note I did not restrict data to major transit systems because I was interested in seeing the results despite the size of the transit system

Q1. Which transit system (agency and mode) had the most UPT in 2022?
The transit system with the most UPT in 2022 was the MTA New York City Transit

```
{r echo=TRUE, warning=FALSE, message=FALSE}
USAGE_2022_ANNUAL |>
  group_by(Agency, Mode) |>
  arrange(desc(UPT_Total)) |>
  head(5) |>
  ungroup()

```
Q2. Which transit system (agency and mode) had the highest farebox recovery, defined as the highest ratio of Total Fares to Expenses?

The Agency Transit Authority of Central Kentucky with the mode of Vanpool had the highest farebox recovery. This indicates that this agency was able to obtain more revenue relative to its expenses in comparison to other Agencies. It its interesting to see that Vanpool occupies the second and third place in this query. This might indicate that this is Mode of transportation is financially efficient


```
{r echo=TRUE, warning=FALSE, message=FALSE}
highest_farebox_recovery <- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarise(ratio = (sum(`Total Fares`, na.rm = TRUE)/sum(Expenses, na.rm = TRUE))) |>
  ungroup() |>
  arrange(desc(ratio)) |>
  head(5)

print(highest_farebox_recovery)

```
Q3. Which transit system (agency and mode) has the lowest expenses per UPT?

North Carolina State University's Bus transportation had the lowest expenses per UPT. This seems to be a transit system focusing on transportation for a university, so it might be that the low expenses derive from the relative short range of the service provided

```
{r echo=TRUE, warning=FALSE, message=FALSE}
lowest_expenses_per_UPT <- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarise(ratio = (sum(Expenses, na.rm = TRUE)/sum(UPT_Total, na.rm = TRUE)),.groups = "drop") |>
  arrange(ratio) |>
  head(5)
print(lowest_expenses_per_UPT)

```
Q4. Which transit system (agency and mode) has the highest total fares per UPT?

The Altoona Metro Transit Demand Response transportation had the highest total fares per UPT

```
{r echo=TRUE, warning=FALSE, message=FALSE}
highest_total_fares_per_UPT <- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarise(ratio = (sum(`Total Fares`, na.rm = TRUE)/sum(UPT_Total, na.rm = TRUE)),.groups = "drop") |>
  arrange(desc(ratio)) |>
  head(5)
print(highest_total_fares_per_UPT) 

```

Q5. Which transit system (agency and mode) has the lowest expenses per VRM?

New Mexico Department of Transportation Vanpool mode had the lowest expense per VRM. That same mode is in the next 4 spots of our results. This indicates that Vanpool could be transportation mode that does not require or demands a lot of expenses.

```
{r echo=TRUE, warning=FALSE, message=FALSE}
lowest_expenses_per_VRM <- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarise(ratio = (sum(Expenses, na.rm = TRUE)/sum(VRM_Total, na.rm = TRUE)),.groups = "drop") |>
  arrange(ratio) |>
  head(5)
print(lowest_expenses_per_VRM)

```

Q6. Which transit system (agency and mode) has the highest total fares per VRM?

Chicago Water Taxi (Wendella) Ferryboat transportation had the highest total fares per VRM. This might reflect the fact that expenses and mainteinance for this mode of transportation is higher

```
{r echo=TRUE, warning=FALSE, message=FALSE}
highest_fares_per_VRM <- USAGE_AND_FINANCIALS |>
  group_by(Agency, Mode) |>
  summarise(ratio = (sum(`Total Fares`, na.rm = TRUE)/sum(VRM_Total, na.rm = TRUE)),.groups = "drop") |>
  arrange(desc(ratio)) |>
  head(5)
print(highest_fares_per_VRM)

```

##Conclusion
Farebox recovery rate for the Transit Authority of Central Kentucky, and more specifically the Vanpool mode seems to be great. There should be a deeper investigation into why this is, and how this transportation mode can be escalated to serve more people, or how Vanpool transportation mode's characteristics can be leveraged for other transportation modes to achieve such recovery rates